#!/bin/bash

#DIRECTORY=$(dirname "$0")
#echo "Changing to ${DIRECTORY}"
#cd  "$DIRECTORY" || exit 1

echo "Compile your project here"
#pwd
#pip install -e .
pip install dnslib
pip install requests
pip install cryptography
pip install flask
pip install pycryptodome